### ISSUE TITLE
Error when running project on MacOS 11.6

### ISSUE THREAD

**Issue by dimitriedavid** [UPB-Graphics/gfx-framework#11]
I have followed every step from the README and I get the following error when running `./bin/Debug/GFXFramework`:

```
dyld: Library not loaded: /mnt/c/Users/Florin/Desktop/egc/Framework-EGC/src/components_hidden/build/macos-x86_64/bin/Release/GFXComponents.dylib
  Referenced from: /Users/dimi/fac/egc/gfx-framework-master/build/bin/Debug/./GFXFramework
  Reason: image not found
[1]    22458 abort      ./GFXFramework
```

I guess there is a hardcoded reference in a prebuilt dependency.
I can give any additional information in order to solve this.

Thank you!

**Comment by dimitriedavid** [comment]
I found out the problem might be in the prebuilt GFXComponents.dylib file.
I found out using
```
$ grep -rnw './' --exclude-dir=build -e '/mnt/c/Users/Florin/Desktop/egc/Framework-EGC/src/components_hidden/build/macos-x86_64/bin/Release/GFXComponents.dylib'
```
And got
```
Binary file .//deps/prebuilt/GFXComponents/x86_64/GFXComponents.dylib matches
```

**Comment by flriancu** [comment]
Please test with the `bugfix/macos-dylib` branch.

**Comment by flriancu** [comment]
As an aside, please note the following: the framework was not fully tested with macOS during development as it was (and still is) lowest priority.

This fact, coupled with Apple's non-compliant implementation of some OpenGL functions, may result in unexpected behavior.

So, if you do encounter something that doesn't work, and the staff does not have time to address the issue, you may need to use Windows or Linux in the mean time, or take debugging into your own hands. In any case, I encourage you to file issues with any aspect that doesn't work properly. Thanks!

**Comment by dimitriedavid** [comment]
I tested with the `bugfix/macos-dylib` branch and it is working accordingly. Thank you!

I am aware that the macOS support is experimental and I am ready to debug any problem. If I encounter any unexpected behavior that I cannot fix, I will switch to Windows.
