### ISSUE TITLE
Library not found on MacOS 11.6

### ISSUE THREAD

**Issue by BiancaIalangi** [UPB-Graphics/gfx-framework#13]
I have followed every step from README, but when I am building the project I get the following error:

```
ld: library not found for -lGLEW
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/Debug/GFXFramework] Error 1
make[1]: *** [CMakeFiles/GFXFramework.dir/all] Error 2
make: *** [all] Error 2
```
I checked and the GLEW library is installed.

Thank you!

**Comment by flriancu** [comment]
@BiancaIalangi please test the updated master branch. It contains PR #19 , which I suspect fixes the issue. Thanks!

**Comment by BiancaIalangi** [comment]
Solved! Everything works fine. Thank you!
