### ISSUE TITLE
Retina Display

### ISSUE THREAD

**Issue by teo0paiu0fil** [UPB-Graphics/gfx-framework#27]
The ppi in the macbook retina display affects the glViewport function and scales down the objects in the window.

<img width="1383" alt="image" src="https://github.com/UPB-Graphics/gfx-framework/assets/83132852/4db538d6-d516-4832-93fb-7be9fbf011d6">

as seen here the scene is half witdh and height , but as soon as i double the resolution only for the glViewport like so:

<img width="636" alt="image" src="https://github.com/UPB-Graphics/gfx-framework/assets/83132852/00934881-c817-47a8-aa3c-140a5a5372bb">

this is the result:

<img width="1323" alt="image" src="https://github.com/UPB-Graphics/gfx-framework/assets/83132852/51dcbd5b-687a-49ab-85ac-10ab80e8b34e">

This is a thread that gave me the idea to double the rezolution.

**Comment by teo0paiu0fil** [comment]
https://stackoverflow.com/questions/36672935/why-retina-screen-coordinate-value-is-twice-the-value-of-pixel-value
i forgot to add it.

**Comment by teo0paiu0fil** [comment]
as it is now it won't be a problem for futere lab's
but when it come's to the homeworks a person that will open such a project with this fix will get a window with the viewport overflowed

**Comment by flriancu** [comment]
@teo0paiu0fil What commit did you run? I made [this one](https://github.com/UPB-Graphics/gfx-framework/commit/fe68fcbbd55a33926bcb3d4284f9c14c40e69ff9) last week, which should have fixed the issue.

**Comment by flriancu** [comment]
Closing due to no response, reopen if necessary.
