### ISSUE TITLE
Varying "texture_coord" has different type qualifier across different shaders.

### ISSUE THREAD

**Issue by vladtf** [UPB-Graphics/gfx-framework#28]
When running the app this exception is thrown:
`FILE = C:\Personal\gfx-framework\build\bin\Debug\src\lab_m2\lab3\shaders\ShadowMappingPassTwo.FS.glsl    ..... COMPILED
Shader Loader : LINK ERROR
Varying "texture_coord" has different type qualifier across different shaders.`

Had to change this line for it to work:
https://github.com/UPB-Graphics/gfx-framework/blob/67bc8c574468837037ce33cf9027e193975132bd/src/lab_m2/lab3/shaders/ShadowMappingPassTwo.FS.glsl#L4

Fixed version:
`layout(location = 0) in vec2 texture_coord;`

The same issue for: `ShadowMappingPassOne.FS.glsl`

CC: @maritim

**Comment by maritim** [comment]
Hi @vladtf !

Thank you for reporting the problem! We also noticed it during the activities of the previous week and apparently, it occurs only for some graphics processing units. We planned to fix the problem by the beginning of the following week. Thank you for the effort to report the problem, we appreciate it :).

I made a pull request that fixes the error.

All the best!
